### ISSUE TITLE
Slide collision response teleports an item

### ISSUE THREAD

**Issue by mtdowling** [kikito/bump.lua#37] opened 2017-05-29 18:46 UTC
This issue is related to https://github.com/kikito/bump.lua/pull/28.

When you use a "slide" collision response, it can attempt to slide the item in the opposite direction that you wanted to go. I wonder if slide should automatically clamp its response to not send the item backwards.

Here's an example of how slide can teleport an item: in my game there are arrows on the ground that point in a specific direction. The player can walk over the arrow as long as they are not walking in the opposite direction it points. Given an arrow pointing to the right, the player can walk up through the arrow, down through the arrow, right through the arrow, but not left against the arrow. If the player walks down, entering the arrow midway though it, and then attempts to walk left (against the arrow), the player will teleport backward all the way to the far right of the arrow. The desired response would have been to just reject the movement but keep the player at the same x position.

![teleportation-bump](https://cloud.githubusercontent.com/assets/190930/26559395/2980b5d2-4464-11e7-8f25-1bd4d0f0c494.gif)

My hacky solution I provided in https://github.com/kikito/bump.lua/pull/28 attempted to circumvent this, but I think there's got to be a better solution for this.

**Comment by kikito** [comment] 2017-05-30 11:42
Hi, thanks for taking the time to write the issue and even produce a video exemplifying the problem. It is one of the best issues I've had so far on my open source projects.

However, I must reject this. 

Bump tries to follow the 80/20 rule as much as possible. From my understanding the behaviour you are seeing is what someone would expect by default. In particular, people making platformers expect their characters to "bump up" platforms when they "go through them" via gravity. They don't expect the characters to "suddenly get stuck inside a platform".

In your particular case, the way I would solve the problem is twofold: first, I would use "cross" instead of "slide". Then I would use a filter so the collision with each arrow is triggered only when the player's velocity is appropriate. And then I would reset the player's velocity when the collision is detected.

Again, thanks a lot for your efforts in creating this issue. Your game looks quite original. I will close this issue now. Let me know if you need further assistance on this.

**Closed by kikito** 2017-05-30 11:42 UTC

**Comment by mtdowling** [comment] 2017-05-31 04:58
Glad you appreciated the issue, and thanks for the suggestion on how to overcome this! 😄 

These arrows aren't the only place I see teleportation when using bump; I also run into it when trying to move into a corner where two squares connect. The player sort of vibrates on the corner, and if any other NPCs or projectiles hit the player, he can sometimes teleport off of the map. I wouldn't be surprised if the root cause of the issues you are running into on #28 are directly related this is issue.

I also don't want the player to ever teleport intentionally into something that is impassible. If I understand your response correctly, that's sort of the scenario you outlined as a defense for why the slide response does this. In my game, I try to prevent these types of scenarios from happening by checking if an entity can move somewhere before updating its position. I would never run into a use case where I expect the entity to teleport from inside of an impassible obstacle because I'd never place them in one.

My suggestion would be to consider adding a collision response like slide but that does not teleport an entity.

**Comment by mtdowling** [comment] 2017-05-31 06:27
I played around with the library, and I was able to prevent teleportation. I don't really understand why this change works though:

```diff
diff --git a/vendor/bump.lua b/vendor/bump.lua
index 764d55d..b4a61a9 100644
--- a/vendor/bump.lua
+++ b/vendor/bump.lua
@@ -174,10 +174,13 @@ local function rect_detectCollision(x1,y1,w1,h1, x2,y2,w2,h2, goalX, goalY)
       tx, ty = x1 + px, y1 + py
     else
       -- intersecting and moving - move in the opposite direction
+      --[[
       local ti1, _
       ti1,_,nx,ny = rect_getSegmentIntersectionIndices(x,y,w,h, 0,0,dx,dy, -math.huge, 1)
       if not ti1 then return end
       tx, ty = x1 + dx * ti1, y1 + dy * ti1
+      --]]
+      tx, ty = x1 + dx, y1 + dy
     end
   else -- tunnel
     tx, ty = x1 + dx * ti, y1 + dy * ti
```
Do you have any links you could point me to for the math on how this works? Is this related to Minkowski differences?

**Comment by mtdowling** [comment] 2017-07-12 05:30
Just a quick follow up here: I figured out that I could just use custom collision responses here that mimic slide, but prevents movement deltas in a specific direction (e.g., "block-left", "block-right", etc.).
